[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
name = "jsonrow2csv"
version = "0.1.0"

[dependencies]
clap = "2.23.3"
csv = "1.0.0-beta.1"
json = "0.11.6"
slog = "2.0.2"
slog-async = "2.0.1"
slog-stdlog = "2.0.0-3.0"
slog-term = "2.0.0-4.0"
